refactor(fzf_bindings): refactor `__fzf_git_file_open` [see commit body for details]
- Improve printf implementation
- Capture exit code in FZF_BINDINGS_LAST_STATUS

diff --git a/dot_fzf_bindings b/dot_fzf_bindings
--- a/dot_fzf_bindings
+++ b/dot_fzf_bindings
@@ -265,45 +265,57 @@ builtin bind -m vi-command '"\C-xx": "i\C-x0\C-_01\C-x1\C-x2\015"'
 
 # "<C-g>f" - open any git-tracked file in the project.
 __fzf_git_file_open() {
-  trap '__catch_interrupt "$cwd"' ERR INT TERM QUIT
-
   local project_root
   if ! project_root="$(git rev-parse --show-toplevel 2>/dev/null)"; then
-    builtin printf "%s\n" "__fzf_git_file_open: Not in a git-tracked project" 2>&1
-    return 1
+    printf "Warning: '%s' couldn't detect a Git project.\n" "${FUNCNAME[0]}" >&2
+    FZF_BINDINGS_LAST_STATUS=1
+    return $FZF_BINDINGS_LAST_STATUS
   fi
 
   local -r fzf_keys="ctrl-o,ctrl-x,ctrl-v,ctrl-t,ctrl-s,alt-c,ctrl-c"
-  local fzf_height_40="40%"
+  local -r fzf_height_40="40%"
+
   local -a selection
   mapfile -t selection < <(
-    FZF_DEFAULT_COMMAND="${FZF_DEFAULT_COMMAND}" \
-      command git -C "$project_root" ls-files |
-      command fzf --height="$fzf_height_40" -0 --expect="$fzf_keys"
+    git -C "$project_root" ls-files |
+      fzf --height="$fzf_height_40" -0 --expect="$fzf_keys"
   )
 
-  local key="${selection[0]}"
-  [[ $key == "ctrl-c" ]] && return 127
+  local -r key="${selection[0]}"
+  if [[ "$key" == "ctrl-c" ]]; then
+    FZF_BINDINGS_LAST_STATUS=127
+    return $FZF_BINDINGS_LAST_STATUS
+  fi
 
   local file="${selection[1]}"
-  [[ -z $file ]] && return 1
+  if [[ -z "$file" ]]; then
+    FZF_BINDINGS_LAST_STATUS=1
+    return $FZF_BINDINGS_LAST_STATUS
+  fi
 
   local path="${project_root}/${file}"
-  local -r realpath_cmd=$(
-    if command -v realpath &>/dev/null && command realpath --version &>/dev/null 2>&1; then
-      command -v realpath
-    else
-      command -v grealpath || :
-    fi
-  )
+  local realpath_cmd
+  if command realpath --version &>/dev/null 2>&1; then
+    realpath_cmd="$(command -v realpath)"
+  else
+    realpath_cmd="$(command -v grealpath || true)"
+  fi
+
+  local path="${project_root}/${file}"
   [[ -n $realpath_cmd ]] && path="$($realpath_cmd --relative-to="$(pwd)" "$path")"
-  [[ -f $path ]] || return 1
+
+  if [[ ! -f $path ]]; then
+    FZF_BINDINGS_LAST_STATUS=1
+    return $FZF_BINDINGS_LAST_STATUS
+  fi
 
   local cmd
-  cmd="$(__build_edit_command -k "$key" -t "$EDITOR_CMD" -f "$path")" || return 1
-  __insert_text_at_cursor "$cmd"
+  if ! cmd="$(__build_edit_command -k "$key" -t "$EDITOR_CMD" -f "$path")"; then
+    FZF_BINDINGS_LAST_STATUS=1
+    return $FZF_BINDINGS_LAST_STATUS
+  fi
 
-  trap - ERR INT TERM QUIT
+  __insert_text_at_cursor "$cmd"
 }
 builtin bind -x '"\C-_15": __fzf_git_file_open'
 builtin bind -m vi-insert '"\C-gf": "\C-x0\C-_15\C-x1\C-x2\015"'
